name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Fetch repository
        run: git fetch origin

      - uses: pre-commit/action@v3.0.1
        with:
          # extra_args: --from-ref origin/HEAD --to-ref HEAD
          # extra_args: --from-ref main --to-ref HEAD
          # extra_args: --from-ref main
          extra_args: --from-ref origin/main --to-ref HEAD
